variable_labels = {'met_et':r'$\mathrm{E_{T}^{miss}}$ [GeV]',
                      'Mllll':r'$\mathrm{m_{4l}}$ [GeV]',
                      'mll':r'$\mathrm{m_{ll}}$ [GeV]',
                      'myy':r'$\mathrm{m_{\gamma\gamma}}$ [GeV]',
                   'ptll':r'$\mathrm{p_{T}^{ll}}$ [GeV]',
                   'delta_eta_ll':r'$\mathrm{\Delta\eta_{ll}}$',
                   'delta_phi_ll':r'$\mathrm{\Delta\phi_{ll}}$',
                   'jet_n':r'$\mathrm{N_{jets}}$',
                   'bjet_n':r'$\mathrm{N_{b-jets}}$',
                   'Channel':'Channel',
                   'SumCharges':r'$\mathrm{\Sigma}$ charge',
                   'MinmOCST':r'min $\mathrm{M_{OCST}}$',
                   'LepPt0':r'$\mathrm{p_{T}^{lep0}}$ [GeV]',
                   'LepPt1':r'$\mathrm{p_{T}^{lep1}}$ [GeV]',
                   'LepPt2':r'$\mathrm{p_{T}^{lep2}}$ [GeV]',
                   'LepPt3':r'$\mathrm{p_{T}^{lep3}}$ [GeV]',
                   'MZ1':r'$\mathrm{M_{Z1}}$ [GeV]',
                   'MZ2':r'$\mathrm{M_{Z2}}$ [GeV]'
}
